// <auto-generated />
using System;
using BookingMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingMVC.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingMVC.Models.Grad", b =>
                {
                    b.Property<int>("IdGrad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrad"));

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdGrad");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("BookingMVC.Models.Korisnik", b =>
                {
                    b.Property<int>("IdKorisnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKorisnik"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdUloga")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdKorisnik");

                    b.HasIndex("IdUloga");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("BookingMVC.Models.ListaZelja", b =>
                {
                    b.Property<int>("IdListaZelja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdListaZelja"));

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("int");

                    b.Property<int>("IdSmjestaj")
                        .HasColumnType("int");

                    b.HasKey("IdListaZelja");

                    b.HasIndex("IdKorisnik");

                    b.HasIndex("IdSmjestaj");

                    b.ToTable("ListaZelja");
                });

            modelBuilder.Entity("BookingMVC.Models.Notifikacija", b =>
                {
                    b.Property<int>("IdNotifikacija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotifikacija"));

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNotifikacija");

                    b.HasIndex("IdKorisnik");

                    b.ToTable("Notifikacije");
                });

            modelBuilder.Entity("BookingMVC.Models.Poruka", b =>
                {
                    b.Property<int>("IdPoruka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPoruka"));

                    b.Property<int>("IdPosiljalac")
                        .HasColumnType("int");

                    b.Property<int>("IdPrimalac")
                        .HasColumnType("int");

                    b.Property<bool>("Procitana")
                        .HasColumnType("bit");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VrijemeSlanja")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPoruka");

                    b.HasIndex("IdPosiljalac");

                    b.HasIndex("IdPrimalac");

                    b.ToTable("Poruke");
                });

            modelBuilder.Entity("BookingMVC.Models.Recenzija", b =>
                {
                    b.Property<int>("IdRecenzija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecenzija"));

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("int");

                    b.Property<int>("IdSmjestaj")
                        .HasColumnType("int");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.HasKey("IdRecenzija");

                    b.HasIndex("IdKorisnik");

                    b.HasIndex("IdSmjestaj");

                    b.ToTable("Recenzije");
                });

            modelBuilder.Entity("BookingMVC.Models.Rezervacija", b =>
                {
                    b.Property<int>("IdRezervacija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRezervacija"));

                    b.Property<int>("BrojOsoba")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumOdjave")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("int");

                    b.Property<int>("IdSmjestaj")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.HasKey("IdRezervacija");

                    b.HasIndex("IdKorisnik");

                    b.HasIndex("IdSmjestaj");

                    b.HasIndex("IdStatus");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("BookingMVC.Models.Sadrzaj", b =>
                {
                    b.Property<int>("IdSadrzaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSadrzaj"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdSadrzaj");

                    b.ToTable("Sadrzaji");
                });

            modelBuilder.Entity("BookingMVC.Models.Smjestaj", b =>
                {
                    b.Property<int>("IdSmjestaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSmjestaj"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<int>("BrojOsoba")
                        .HasColumnType("int");

                    b.Property<decimal>("CijenaPoNoci")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("IdAdmin")
                        .HasColumnType("int");

                    b.Property<int>("IdGrad")
                        .HasColumnType("int");

                    b.Property<int>("IdTip")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSmjestaj");

                    b.HasIndex("IdAdmin");

                    b.HasIndex("IdGrad");

                    b.HasIndex("IdTip");

                    b.ToTable("Smjestaji");
                });

            modelBuilder.Entity("BookingMVC.Models.SmjestajSadrzaj", b =>
                {
                    b.Property<int>("IdSmjestaj")
                        .HasColumnType("int");

                    b.Property<int>("IdSadrzaj")
                        .HasColumnType("int");

                    b.HasKey("IdSmjestaj", "IdSadrzaj");

                    b.HasIndex("IdSadrzaj");

                    b.ToTable("SmjestajSadrzaji");
                });

            modelBuilder.Entity("BookingMVC.Models.StatusRezervacije", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatus"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdStatus");

                    b.ToTable("StatusiRezervacija");
                });

            modelBuilder.Entity("BookingMVC.Models.TipSmjestaja", b =>
                {
                    b.Property<int>("IdTipSmjestaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipSmjestaja"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdTipSmjestaja");

                    b.ToTable("TipoviSmjestaja");
                });

            modelBuilder.Entity("BookingMVC.Models.Uloga", b =>
                {
                    b.Property<int>("IdUloga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUloga"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUloga");

                    b.ToTable("Uloge");
                });

            modelBuilder.Entity("BookingMVC.Models.Korisnik", b =>
                {
                    b.HasOne("BookingMVC.Models.Uloga", "Uloga")
                        .WithMany()
                        .HasForeignKey("IdUloga")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("BookingMVC.Models.ListaZelja", b =>
                {
                    b.HasOne("BookingMVC.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("IdKorisnik")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingMVC.Models.Smjestaj", "Smjestaj")
                        .WithMany()
                        .HasForeignKey("IdSmjestaj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Smjestaj");
                });

            modelBuilder.Entity("BookingMVC.Models.Notifikacija", b =>
                {
                    b.HasOne("BookingMVC.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("IdKorisnik")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("BookingMVC.Models.Poruka", b =>
                {
                    b.HasOne("BookingMVC.Models.Korisnik", "Posiljalac")
                        .WithMany()
                        .HasForeignKey("IdPosiljalac")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingMVC.Models.Korisnik", "Primalac")
                        .WithMany()
                        .HasForeignKey("IdPrimalac")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Posiljalac");

                    b.Navigation("Primalac");
                });

            modelBuilder.Entity("BookingMVC.Models.Recenzija", b =>
                {
                    b.HasOne("BookingMVC.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("IdKorisnik")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingMVC.Models.Smjestaj", "Smjestaj")
                        .WithMany()
                        .HasForeignKey("IdSmjestaj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Smjestaj");
                });

            modelBuilder.Entity("BookingMVC.Models.Rezervacija", b =>
                {
                    b.HasOne("BookingMVC.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("IdKorisnik")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingMVC.Models.Smjestaj", "Smjestaj")
                        .WithMany()
                        .HasForeignKey("IdSmjestaj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingMVC.Models.StatusRezervacije", "StatusRezervacije")
                        .WithMany()
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Smjestaj");

                    b.Navigation("StatusRezervacije");
                });

            modelBuilder.Entity("BookingMVC.Models.Smjestaj", b =>
                {
                    b.HasOne("BookingMVC.Models.Korisnik", "Admin")
                        .WithMany()
                        .HasForeignKey("IdAdmin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingMVC.Models.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("IdGrad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingMVC.Models.TipSmjestaja", "TipSmjestaja")
                        .WithMany()
                        .HasForeignKey("IdTip")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Grad");

                    b.Navigation("TipSmjestaja");
                });

            modelBuilder.Entity("BookingMVC.Models.SmjestajSadrzaj", b =>
                {
                    b.HasOne("BookingMVC.Models.Sadrzaj", "Sadrzaj")
                        .WithMany()
                        .HasForeignKey("IdSadrzaj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingMVC.Models.Smjestaj", "Smjestaj")
                        .WithMany()
                        .HasForeignKey("IdSmjestaj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sadrzaj");

                    b.Navigation("Smjestaj");
                });
#pragma warning restore 612, 618
        }
    }
}
